# Convert an R package name to a valid Nix attribute
r_to_nix <- function(name) {
  gsub(".", "_", sub("^(import|assert|inherit|with)$", "r_\\1", name), fixed = TRUE)
}

line <- function(x) cat(x, sep = "\n")

base_packages <- rownames(installed.packages(priority = "base"))

args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 1) {
  stop("invalid argument")
}
snapshot <- as.Date(args)

now <- as.POSIXlt(Sys.time(), tz = "UTC")

# Fetch packages from CRAN
db <- available.packages(
  sprintf("https://mran.revolutionanalytics.com/snapshot/%s/src/contrib", snapshot),
  filters = c("R_version", "OS_type", "duplicates"),
  method = "curl"
)

cran_package_names <- db[, "Package"]
nix_package_names <- r_to_nix(cran_package_names)
versions <- db[, "Version"]
dependencies <- tools::package_dependencies(db[, "Package"], db)
md5_sums <- db[, "MD5sum"]

nix_dependencies <- lapply(dependencies, function(deps) {
  deps <- deps[!deps %in% base_packages]  # Ignore base packages as not on CRAN
  if (length(deps) > 0) {
    paste0("[ ", paste0(r_to_nix(deps), collapse = " "), " ]")
  } else {
    "[ ]"
  }
})

line(sprintf("# This file was generated by cran2nix.R at %s. Do not edit.", now))
line("{ self, mkCranDerive }:")
line(sprintf("let\n  derive = mkCranDerive { snapshot = \"%s\"; };\nin", snapshot))
line("with self; {")
line(
  sprintf(
    "  \"%s\" = derive { name = \"%s\"; version = \"%s\"; md5 = \"%s\"; depends = %s; };",
    nix_package_names,
    cran_package_names,
    versions,
    md5_sums,
    nix_dependencies
  )
)
line("}")
