set nocompatible

set title

" set shiftwidth=4
" set softtabstop=4
" set expandtab


set showcmd "display incomplete commands


" Case insensitive search, except when using capital letters
set ignorecase
set smartcase

" Line break by line break undo in insert mode
inoremap <C-U> <C-G>u<C-U>

set mouse=a

inoremap jk <ESC>

set signcolumn=number

call plug#begin()
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'rust-lang/rust.vim'
Plug 'dense-analysis/ale'
Plug 'LnL7/vim-nix'
call plug#end()

let g:ale_linters = {
      \ 'rust': ['cargo', 'rls']
      \ }
let g:ale_rust_rls_executable = 'rust-analyzer'
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_insert_leave = 1
let g:ale_completion_enabled = 1
let g:ale_rust_cargo_default_feature_behavior = 'all'
