# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/efi" =
    {
      device = "/dev/disk/by-uuid/BD51-5304";
      fsType = "vfat";
      # Use automount for data safety https://0pointer.net/blog/linux-boot-partitions.html
      options = [ "x-systemd.automount" "x-systemd.idle-timeout=5s" ];
    };

  fileSystems."/" =
    {
      device = "rpool/enc/root";
      fsType = "zfs";
    };

  fileSystems."/root" =
    {
      device = "rpool/enc/roothome";
      fsType = "zfs";
    };

  fileSystems."/home" =
    {
      device = "rpool/enc/home";
      fsType = "zfs";
    };

  fileSystems."/persist" =
    {
      device = "rpool/enc/persist";
      fsType = "zfs";
      neededForBoot = true;
    };

  fileSystems."/nix" =
    {
      device = "rpool/enc/nix";
      fsType = "zfs";
    };

  fileSystems."/nix/store" =
    {
      device = "rpool/nixstore";
      fsType = "zfs";
    };

  fileSystems."/var/log" =
    {
      device = "rpool/enc/log";
      fsType = "zfs";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s20f0u5u2c2.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
