name: "nix"

on:
  push:
  
  pull_request:
    branches:
      - main

  schedule:
    - cron: '9 9 * * *'

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    
    - uses: cachix/cachix-action@v12
      with:
        name: james-atkins
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        pushFilter: "(-source$|-wrapper$|\\.deb$|\\.tar\\.xz$|\\.tar\\.gz$|\\.zip$|\\.patch$)"

    - name: Flake registry update
      run: wget https://github.com/NixOS/flake-registry/raw/master/flake-registry.json -O flake-registry.json
      if: ${{ github.event_name == 'schedule' || github.event_name == 'pull_request' }}

    - name: Flake update
      run: nix flake update
      if: ${{ github.event_name == 'schedule' || github.event_name == 'pull_request' }}
    
    - name: Build all machines
      run: nix flake show --json | jq --raw-output '.nixosConfigurations | keys[]' | xargs -L1 -I'{}' nix build --print-build-logs .#nixosConfigurations.{}.config.system.build.toplevel
    
    - name: Commit and push
      run: |-
        git config user.name "GitHub Actions"
        git config user.email "actions@users.noreply.github.com"
        git add flake.lock
        git commit -m "[Auto] Package updates" || exit 0
        git push
      if: ${{ github.event_name == 'schedule' || github.event_name == 'pull_request' }}
