name: "nix"

on:
  push:
  
  pull_request:
    branches:
      - main

  schedule:
    - cron: '9 9 * * *'

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - uses: cachix/install-nix-action@v13
      with:
        install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
        install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
        extra_nix_config: |
          experimental-features = nix-command flakes
    
    - uses: cachix/cachix-action@v10
      with:
        name: james-atkins
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    
    - name: Flake update
      run: nix flake update
      if: ${{ github.event_name == 'schedule' || github.event_name == 'pull_request' }}
    
    - name: Build all packages
      run: nix build --verbose --print-build-logs .#allPackages
    
    - name: Commit and push
      run: |-
        git config user.name "GitHub Actions"
        git config user.email "actions@users.noreply.github.com"
        git add flake.lock
        git commit -m "[Auto] Package updates" || exit 0
        git push
      if: ${{ github.event_name == 'schedule' || github.event_name == 'pull_request' }}
